services:

  swagger-ui:
    container_name: swagger-ui
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    environment:
      - API_URL=http://localhost:3000/

  postgres-rest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      - PGRST_DB_URI=postgres://everframe:everframe@postgres:5432/everframe_db
      - PGRST_DB_SCHEMA=public
      - PGRST_DB_ANON_ROLE=web_anon
      - PGRST_OPENAPI_SERVER_PROXY_URI=http://localhost:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=everframe_db
      - POSTGRES_USER=everframe
      - POSTGRES_PASSWORD=everframe
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U everframe -d everframe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: